### ISSUE TITLE
Vehicle departs too soon

### ISSUE THREAD

**Issue by Gregory365** [Gregory365/TPF2-Timetables#38]
Related to #27 

Timetable:
Arrival 05 -> Departure 30
Arrival 35 -> Departure 00

The frequency with 3 trains is 22 minutes, with 2 trains it's 33.

I observed a train departing at 30 as expected. Then shortly after 35 the next one arrived and I would have expected it to wait until 00 but it left after it's min. wait time.

A train arriving shortly after 30 should always fall into the (Arrival 35 -> Departure 00) slot
(with this timetable setup)

**Comment by IKatsu** [comment]
I am also noticing something similar.
It -looks- like a train arriving is also rounding down to the nearest departure time instead of only rounding up to the next departure time which is causing them to leave outside of the schedule.
I have a train line set on a 5 minute schedule to try and get a better spread and trains will keep departing up to around 2 minutes after the previous train already left.
Train departed at 00:06, next train moves into the station at 00:07 and will immediately depart after a few seconds. Train arriving at 00:08 will wait for the 00:10-00:11 schedule.
I have it set to minimal waiting time and no maximum waiting time.

**Comment by Gregory365** [comment]
Just to give the status of this issue. I can't reproduce this myself. I think it's a combination of a narrow timetable (arrival and departure times are close together), an uncertain arrival time (vehicles don't arrive within the scheduled window) and a large min wait time (vehicles are forced to stay longer that their departure slot, inhibiting the arrival of the next train).

There are four ways to solve this:
1. Remove the minimum wait time (so late vehicles can leave earlier)
I would suggest this be, at most, half the difference between the arrival and departure time
2. Make the arrival time earlier (so vehicles have a longer window to arrive in)
I would suggest half-way in between the departure times.
3. Add alternative platforms (so vehicles don't get blocked from arriving)
4. Ease congestion on the line (so vehicles don't arrive late as often)

So to clarify, the timetable would look like this:
Arrival -> Departure
03:30 -> 06:00
08:30 -> 11:00
13:30 -> 16:00
...
53:30 -> 56:00
min. wait time <= 01:15
max. wait time >= 2:30 [I would recommend this be disabled anyway]

**Comment by Gregory365** [comment]
Added test to see if first issue still exists, and the vehicle waits until 00:00 as expected.
If you are still experiencing this issue, read the advice in the previous comment first, 
and if that is unsuccessful, please raise a new issue.
